# Generated by Django 3.1.6 on 2021-02-05 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_auto_20210204_2042'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Flights',
            new_name='Flight',
        ),
    ]
